# This job will run and scan and notify.
name: scan market

on:
   schedule:
     - cron: '0 13 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CHAT_ID_AND_TEXT: ${{ secrets.CHAT_ID_AND_TEXT }}
      SCANNER_URL: ${{ secrets.SCANNER_URL }}
      SCREENER_ONE_URL: ${{ secrets.SCREENER_ONE_URL }}
      SCREENER_TWO_URL: ${{ secrets.SCREENER_TWO_URL }}
      SCREENER_THREE_URL: ${{ secrets.SCREENER_THREE_URL }}
      SEND_MESSAGE_URL: ${{ secrets.SEND_MESSAGE_URL }}
      MODE: MARKET
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -Dmaven.test.skip=true -B package --file pom.xml  

    - name: Run
      run: |
        java -jar target/notifier-0.0.1-SNAPSHOT.jar
